name: Deploy React App to EC2 with Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Copy files to EC2 and reload Nginx
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > streaky.pem
          chmod 400 streaky.pem

          # Clean old build directory
          ssh -o StrictHostKeyChecking=no -i streaky.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo rm -rf /var/www/html/*"

          # Copy new build folder
          scp -o StrictHostKeyChecking=no -i streaky.pem -r dist/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html/

          # Reload Nginx
          ssh -o StrictHostKeyChecking=no -i streaky.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo systemctl reload nginx"

        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
