name: Deploy to EC2

on:
  push:
    branches: [ main ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Test GitHub Actions
      env:
        USER: ${{secrets.EC2_USER}}
      run: 
        echo "Hello from GitHub Actions"
        echo $USER
